name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - "*.*.*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  oversize-components:
    name: Build OversizeComponents
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm-all-platforms.yml@main
    if: "!startsWith(github.ref, 'refs/tags/')"
    with:
      package: OversizeComponents
    secrets: inherit
    
  oversize-health-components:
    name: Build OversizeHealthComponents
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm-all-platforms.yml@main
    if: "!startsWith(github.ref, 'refs/tags/')"
    with:
      package: OversizeHealthComponents
    secrets: inherit
    
  oversize-photo-components:
    name: Build OversizePhotoComponents
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm-all-platforms.yml@main
    if: "!startsWith(github.ref, 'refs/tags/')"
    with:
      package: OversizePhotoComponents
    secrets: inherit
    
  oversize-weather-components:
    name: Build OversizeWeatherComponents
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm-all-platforms.yml@main
    if: "!startsWith(github.ref, 'refs/tags/')"
    with:
      package: OversizeWeatherComponents
    secrets: inherit

  tests:
    name: Test
    needs:
      - oversize-components
      - oversize-health-components
      - oversize-photo-components
      - oversize-weather-components
    uses: oversizedev/GithubWorkflows/.github/workflows/test.yml@main
    secrets: inherit
    
  bump:
    name: Bump version
    needs: tests
    if: github.ref == 'refs/heads/main'
    uses: oversizedev/GithubWorkflows/.github/workflows/bump.yml@main
    secrets: inherit

  release:
    name: Create Release
    if: github.ref != 'refs/heads/main' && startsWith(github.ref, 'refs/tags/')
    uses: oversizedev/GithubWorkflows/.github/workflows/release.yml@main
    secrets: inherit
