name: CI - Push

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-swiftpm:
    name: Build packages
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm.yml@main
    strategy:
      matrix:
        packages: [OversizeComponents, OversizeHealthComponents, OversizePhotoComponents, OversizeWeatherComponents]
    with:
      package: ${{ matrix.packages }}
    secrets: inherit
    
  bump:
    name: Bump version
    needs: tests
    uses: oversizedev/GithubWorkflows/.github/workflows/bump.yml@main
    secrets: inherit
